In [2]:
import numpy as np

In [3]:
arr1 = np.array([-9, 7, 4 ,3])

In [4]:
arr1

array([-9,  7,  4,  3])

In [5]:
arr2 = np.array([-9, 7, 4, 3], dtype='str')

In [6]:
arr2

array(['-9', '7', '4', '3'], dtype='<U2')

In [7]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.linspace(1,10,10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [11]:
np.logspace(1,5,base=2,num=10)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
2 ** np.linspace(1,5,10)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [14]:
np.zeros([4,5])  # 四行五列

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones([7,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [17]:
np.diag([4,5,8])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 8]])

In [18]:
np.diag([4,5,8]) + 1

array([[5, 1, 1],
       [1, 6, 1],
       [1, 1, 9]])

In [19]:
arr3.shape

(3, 4)

In [20]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr3.ndim

2

In [23]:
arr1.shape

(4,)

In [24]:
arr1.ndim

1

In [25]:
arr1.size

4

In [26]:
arr3.dtype

dtype('int32')