In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
vector = np.dot(a,b)

In [4]:
vector

32

In [5]:
arr5 = np.array([5,15,25,40]).reshape(4,1)

In [6]:
arr5

array([[ 5],
       [15],
       [25],
       [40]])

In [7]:
arr6 = np.arange(12).reshape(3,4)

In [8]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
arr2d = np.dot(arr6,arr5)

In [10]:
arr2d

array([[185],
       [525],
       [865]])

In [11]:
arr9 = np.array([[6,-1],[8,1]])

In [12]:
arr10 = np.array([[6,10],[-1,1]])

In [13]:
arr9

array([[ 6, -1],
       [ 8,  1]])

In [14]:
arr10

array([[ 6, 10],
       [-1,  1]])

In [15]:
np.dot(arr9,arr10)

array([[37, 59],
       [47, 81]])

In [16]:
arr9 * arr10

array([[ 36, -10],
       [ -8,   1]])

In [20]:
data = ((8.5,6,4.1,2,0.7),(1.5,3,5.4,7.3,9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19.0),(12,3.4,1.2,4.,7))

In [21]:
arr2 = np.array(data)

In [22]:
arr2

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3. ,  5.4,  7.3,  9. ],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ],
       [12. ,  3.4,  1.2,  4. ,  7. ]])

In [24]:
arr2_inv = np.linalg.inv(arr2)

In [26]:
arr2_inv

array([[ 0.38359225,  0.64678839, -0.05443105, -0.30615646,  0.03103458],
       [-1.03934264, -2.12682227,  0.14848718,  0.94615147,  0.07938253],
       [ 1.0515443 ,  1.83717063, -0.02841689, -0.82191   , -0.19979637],
       [-0.06418152,  0.00269982, -0.20624469,  0.09432912,  0.0120825 ],
       [-0.29635273, -0.39223843,  0.14391361,  0.15227685,  0.0784443 ]])

In [27]:
np.dot(arr2,arr2_inv)

array([[ 1.00000000e+00,  3.33066907e-16, -6.93889390e-17,
        -3.60822483e-16,  1.24900090e-16],
       [ 4.44089210e-16,  1.00000000e+00,  2.22044605e-16,
        -4.44089210e-16,  0.00000000e+00],
       [ 4.44089210e-16,  1.33226763e-15,  1.00000000e+00,
        -4.44089210e-16,  0.00000000e+00],
       [-8.88178420e-16,  0.00000000e+00,  4.44089210e-16,
         1.00000000e+00,  4.44089210e-16],
       [ 4.44089210e-16,  4.44089210e-16,  0.00000000e+00,
        -2.22044605e-16,  1.00000000e+00]])

In [33]:
np.set_printoptions(suppress=True)

In [34]:
np.dot(arr2,arr2_inv)

array([[ 1.,  0., -0., -0.,  0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1., -0.,  0.],
       [-0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -0.,  1.]])

In [35]:
np.diag(arr2)

array([ 8.5,  3. ,  6. , 17.8,  7. ])

In [36]:
arr2

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3. ,  5.4,  7.3,  9. ],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ],
       [12. ,  3.4,  1.2,  4. ,  7. ]])

In [38]:
# 3x + 2y + z = 38
# 2x + 3y + z = 34
# x + 2y + 3x + 26

In [39]:
A = np.array([[3,2,1],[2,3,1],[1,2,3]])

In [40]:
A

array([[3, 2, 1],
       [2, 3, 1],
       [1, 2, 3]])

In [45]:
b = np.array([[39],[34],[36]])

In [46]:
b

array([[39],
       [34],
       [36]])

In [47]:
X = np.linalg.solve(A,b)

In [48]:
X

array([[8.42],
       [3.42],
       [6.92]])