In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[0]

1

In [4]:
arr[3:5]

array([4, 5])

In [5]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [6]:
arr[-1]

9

In [7]:
arr[-4:-2]

array([6, 7])

In [8]:
arr[5] = 12
arr

array([ 1,  2,  3,  4,  5, 12,  7,  8,  9])

In [9]:
arr_change = arr
arr_change[1:3] = [17,19]
arr_change

array([ 1, 17, 19,  4,  5, 12,  7,  8,  9])

In [10]:
arr

array([ 1, 17, 19,  4,  5, 12,  7,  8,  9])

In [11]:
arr

array([ 1, 17, 19,  4,  5, 12,  7,  8,  9])

视图上修改，原数据也会发生改变

In [12]:
arr_change = arr.copy()
arr_change[1:3] = [4, 9]
arr

array([ 1, 17, 19,  4,  5, 12,  7,  8,  9])

In [13]:
arr_change

array([ 1,  4,  9,  4,  5, 12,  7,  8,  9])

In [14]:
data2 = ((8.5,6,4.1,2,0.7),(1.5,3.5,4,7,3.9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19))
arr2 = np.array(data2)
arr2

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3.5,  4. ,  7. ,  3.9],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ]])

In [15]:
arr2[2]

array([3.2, 4.5, 6. , 3. , 9. ])

In [16]:
arr2[2,1]

4.5

In [17]:
arr2[:,2:4]

array([[ 4.1,  2. ],
       [ 4. ,  7. ],
       [ 6. ,  3. ],
       [15.6, 17.8]])

In [18]:
arr2[1:3]

array([[1.5, 3.5, 4. , 7. , 3.9],
       [3.2, 4.5, 6. , 3. , 9. ]])

In [19]:
arr2[1:,2:]

array([[ 4. ,  7. ,  3.9],
       [ 6. ,  3. ,  9. ],
       [15.6, 17.8, 19. ]])

In [20]:
arr2[2][1]

4.5

In [21]:
~(arr2>=3.5)

array([[False, False, False,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False]])

In [22]:
arr2[~(arr2>=3.5)]

array([2. , 0.7, 1.5, 3.2, 3. ])

In [23]:
arr2[(arr2 > 3.5) & (arr2 < 10)]

array([8.5, 6. , 4.1, 4. , 7. , 3.9, 4.5, 6. , 9. ])

花式索引

In [24]:
arr2

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3.5,  4. ,  7. ,  3.9],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ]])

In [25]:
arr2[[2,1]]

array([[3.2, 4.5, 6. , 3. , 9. ],
       [1.5, 3.5, 4. , 7. , 3.9]])

In [27]:
arr2[[3,2],[0,1]]

array([11.2,  4.5])

In [28]:
arr2[:,[3,1]]

array([[ 2. ,  6. ],
       [ 7. ,  3.5],
       [ 3. ,  4.5],
       [17.8, 13.4]])

In [29]:
arr2[:,[1]]

array([[ 6. ],
       [ 3.5],
       [ 4.5],
       [13.4]])

In [30]:
arr2[:,1]

array([ 6. ,  3.5,  4.5, 13.4])

In [31]:
arr2[np.ix_([0,-1],[0,1,3])]

array([[ 8.5,  6. ,  2. ],
       [11.2, 13.4, 17.8]])

In [40]:
arr2[[0,-1]][:,[0,1,3]]

array([[ 8.5,  6. ,  2. ],
       [11.2, 13.4, 17.8]])

In [36]:
arr2[[0,-1]][:,[0,1,3]]

array([[ 8.5,  6. ,  2. ],
       [11.2, 13.4, 17.8]])