In [51]:
import numpy as np

In [52]:
data = ((8.5,6,4.1,2,0.7),(1.5,3.5,4,7,3.9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19))

In [53]:
arr = np.array(data)
arr

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3.5,  4. ,  7. ,  3.9],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ]])

In [54]:
arr2 =arr.reshape(10,2)

In [55]:
arr2

array([[ 8.5,  6. ],
       [ 4.1,  2. ],
       [ 0.7,  1.5],
       [ 3.5,  4. ],
       [ 7. ,  3.9],
       [ 3.2,  4.5],
       [ 6. ,  3. ],
       [ 9. , 11.2],
       [13.4, 15.6],
       [17.8, 19. ]])

In [56]:
arr

array([[ 8.5,  6. ,  4.1,  2. ,  0.7],
       [ 1.5,  3.5,  4. ,  7. ,  3.9],
       [ 3.2,  4.5,  6. ,  3. ,  9. ],
       [11.2, 13.4, 15.6, 17.8, 19. ]])

In [57]:
arr.shape = (10,2)
arr

array([[ 8.5,  6. ],
       [ 4.1,  2. ],
       [ 0.7,  1.5],
       [ 3.5,  4. ],
       [ 7. ,  3.9],
       [ 3.2,  4.5],
       [ 6. ,  3. ],
       [ 9. , 11.2],
       [13.4, 15.6],
       [17.8, 19. ]])

In [58]:
arr.ravel()

array([ 8.5,  6. ,  4.1,  2. ,  0.7,  1.5,  3.5,  4. ,  7. ,  3.9,  3.2,
        4.5,  6. ,  3. ,  9. , 11.2, 13.4, 15.6, 17.8, 19. ])

In [59]:
arr.ravel(order='F')

array([ 8.5,  4.1,  0.7,  3.5,  7. ,  3.2,  6. ,  9. , 13.4, 17.8,  6. ,
        2. ,  1.5,  4. ,  3.9,  4.5,  3. , 11.2, 15.6, 19. ])

In [60]:
arr.flatten(order='F')

array([ 8.5,  4.1,  0.7,  3.5,  7. ,  3.2,  6. ,  9. , 13.4, 17.8,  6. ,
        2. ,  1.5,  4. ,  3.9,  4.5,  3. , 11.2, 15.6, 19. ])

In [61]:
arr.reshape(2,-1)

array([[ 8.5,  6. ,  4.1,  2. ,  0.7,  1.5,  3.5,  4. ,  7. ,  3.9],
       [ 3.2,  4.5,  6. ,  3. ,  9. , 11.2, 13.4, 15.6, 17.8, 19. ]])

In [62]:
arr.reshape(1,-1)

array([[ 8.5,  6. ,  4.1,  2. ,  0.7,  1.5,  3.5,  4. ,  7. ,  3.9,  3.2,
         4.5,  6. ,  3. ,  9. , 11.2, 13.4, 15.6, 17.8, 19. ]])

In [63]:
arr.reshape(-1)

array([ 8.5,  6. ,  4.1,  2. ,  0.7,  1.5,  3.5,  4. ,  7. ,  3.9,  3.2,
        4.5,  6. ,  3. ,  9. , 11.2, 13.4, 15.6, 17.8, 19. ])

In [64]:
arr.flatten()[1] = 1000

In [65]:
arr

array([[ 8.5,  6. ],
       [ 4.1,  2. ],
       [ 0.7,  1.5],
       [ 3.5,  4. ],
       [ 7. ,  3.9],
       [ 3.2,  4.5],
       [ 6. ,  3. ],
       [ 9. , 11.2],
       [13.4, 15.6],
       [17.8, 19. ]])

In [66]:
arr.ravel()[1] = 1000

In [67]:
arr.reshape(-1)[3] = 103

In [68]:
arr

array([[8.50e+00, 1.00e+03],
       [4.10e+00, 1.03e+02],
       [7.00e-01, 1.50e+00],
       [3.50e+00, 4.00e+00],
       [7.00e+00, 3.90e+00],
       [3.20e+00, 4.50e+00],
       [6.00e+00, 3.00e+00],
       [9.00e+00, 1.12e+01],
       [1.34e+01, 1.56e+01],
       [1.78e+01, 1.90e+01]])

reshape, ravel和flatten三个函数中的reshape和ravel会改变视图的结果，但都不会改变形状

In [69]:
arr_t = arr.ravel()
arr_t

array([8.50e+00, 1.00e+03, 4.10e+00, 1.03e+02, 7.00e-01, 1.50e+00,
       3.50e+00, 4.00e+00, 7.00e+00, 3.90e+00, 3.20e+00, 4.50e+00,
       6.00e+00, 3.00e+00, 9.00e+00, 1.12e+01, 1.34e+01, 1.56e+01,
       1.78e+01, 1.90e+01])

In [70]:
arr_t.ndim

1

In [71]:
arr_t.shape

(20,)

In [72]:
arr_t[np.newaxis,:]

array([[8.50e+00, 1.00e+03, 4.10e+00, 1.03e+02, 7.00e-01, 1.50e+00,
        3.50e+00, 4.00e+00, 7.00e+00, 3.90e+00, 3.20e+00, 4.50e+00,
        6.00e+00, 3.00e+00, 9.00e+00, 1.12e+01, 1.34e+01, 1.56e+01,
        1.78e+01, 1.90e+01]])

In [73]:
arr_t[:,np.newaxis].ndim

2

组合

In [74]:
arr1 = np.arange(12).reshape(3,4)

In [75]:
arrl

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
# ((8.5,6,4.1,2,0.7),(1.5,3.5,4,7,3.9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19))

In [77]:
arr2 = np.array([[8.5,6,4.1,2,0.7],[1.5,3.5,4,7,3.9],[3.2,4.5,6,3,9]])

In [78]:
arr2

array([[8.5, 6. , 4.1, 2. , 0.7],
       [1.5, 3.5, 4. , 7. , 3.9],
       [3.2, 4.5, 6. , 3. , 9. ]])

In [79]:
np.hstack([arr1, arr2]).shape

(3, 9)

In [80]:
arr3 = np.array([[8.5,6,4.1,0.9],[1.5,3,5.4,1.1],[3.2,4.5,6,7.3],[11.2,13.4,15.6,14.2]])
arr3

array([[ 8.5,  6. ,  4.1,  0.9],
       [ 1.5,  3. ,  5.4,  1.1],
       [ 3.2,  4.5,  6. ,  7.3],
       [11.2, 13.4, 15.6, 14.2]])

In [81]:
np.vstack((arr1,arr3))

array([[ 0. ,  1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ,  7. ],
       [ 8. ,  9. , 10. , 11. ],
       [ 8.5,  6. ,  4.1,  0.9],
       [ 1.5,  3. ,  5.4,  1.1],
       [ 3.2,  4.5,  6. ,  7.3],
       [11.2, 13.4, 15.6, 14.2]])

In [82]:
np.vstack((arr1,arr3)).shape

(7, 4)

In [83]:
np.concatenate((arr1,arr2),axis=1)  # axis等于1是按着列的方向合并

array([[ 0. ,  1. ,  2. ,  3. ,  8.5,  6. ,  4.1,  2. ,  0.7],
       [ 4. ,  5. ,  6. ,  7. ,  1.5,  3.5,  4. ,  7. ,  3.9],
       [ 8. ,  9. , 10. , 11. ,  3.2,  4.5,  6. ,  3. ,  9. ]])

In [84]:
arr4 = np.array([[0,1],[2,3]])
arr4

array([[0, 1],
       [2, 3]])

In [85]:
np.tile(arr4, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3, 2, 3]])

三维数组

In [86]:
arr5 = np.arange(8).reshape(2,2,2)
arr5

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [90]:
arr5[0]

array([[0, 1],
       [2, 3]])