In [1]:
import numpy as np

In [2]:
arr1 = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])

In [3]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  9],
       [ 1, -3,  4]])

In [4]:
arr2 = np.arange(0,12).reshape(4,3)

In [5]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr1 + arr2 

array([[ 0,  2,  5],
       [ 7,  6, 14],
       [10, 12, 17],
       [10,  7, 15]])

In [7]:
arr3 = np.array([1,2,3])

In [8]:
arr3

array([1, 2, 3])

In [9]:
arr1 + arr3

array([[ 1,  3,  6],
       [ 5,  4, 12],
       [ 5,  7, 12],
       [ 2, -1,  7]])

In [10]:
 arr4 = np.array([[1],[2],[3],[4]])

In [11]:
arr4

array([[1],
       [2],
       [3],
       [4]])

In [12]:
arr1 + arr4

array([[ 1,  2,  4],
       [ 6,  4, 11],
       [ 7,  8, 12],
       [ 5,  1,  8]])

In [13]:
arr5 = np.array([[1,2,3]])

In [14]:
arr5

array([[1, 2, 3]])

In [15]:
arr5.shape

(1, 3)

In [16]:
arr1 + arr5

array([[ 1,  3,  6],
       [ 5,  4, 12],
       [ 5,  7, 12],
       [ 2, -1,  7]])

通用函数

In [17]:
math = np.array([98,83,86,92,67,82])
english = np.array([68,74,66,82,75,89])
chinese = np.array([92,83,76,85,87,77])

In [18]:
total = math + english + chinese

In [19]:
total

array([258, 240, 228, 259, 229, 248])

In [20]:
np.add(np.add(chinese, math),english)

array([258, 240, 228, 259, 229, 248])

In [21]:
np.subtract(math,english)

array([30,  9, 20, 10, -8, -7])

In [22]:
height = np.array([165,177,158,169,173])

In [23]:
weight = np.array([62,73,59,72,80])

In [24]:
weight/(height/100)  ** 2

array([22.77318641, 23.30109483, 23.63403301, 25.20920136, 26.7299275 ])

In [25]:
(weight/(height/100)) ** 2

array([1411.93755739, 1700.97992276, 1394.40794744, 1815.06249781,
       2138.39419961])

In [26]:
np.divide(weight,np.divide(height,100)**2)

array([22.77318641, 23.30109483, 23.63403301, 25.20920136, 26.7299275 ])

In [27]:
np.multiply(height,weight)

array([10230, 12921,  9322, 12168, 13840])

In [28]:
height * weight

array([10230, 12921,  9322, 12168, 13840])

In [29]:
np.power(arr2,3)

array([[   0,    1,    8],
       [  27,   64,  125],
       [ 216,  343,  512],
       [ 729, 1000, 1331]], dtype=int32)

In [30]:
s = np.array([1,2,3,4,3,2,1,2,4,6,7,2,4,8,4,5])

In [31]:
test = [2,4,6]

In [32]:
np.unique(s)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.in1d(s,test)

array([False,  True, False,  True, False,  True, False,  True,  True,
        True, False,  True,  True, False,  True, False])

In [34]:
np.intersect1d(test,s)

array([2, 4, 6])

In [35]:
arr1 = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])

In [36]:
arr2 = np.array([1,2,3])

In [37]:
arr1 == arr2

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [38]:
np.equal(arr1,arr2)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       [ True, False, False]])

In [39]:
np.greater(arr1,arr2)

array([[False, False, False],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [40]:
np.greater(arr1,arr2).any()

True

In [41]:
sl = np.array([-1,1,np.nan])

In [42]:
sl

array([-1.,  1., nan])

In [43]:
np.isnan(sl)

array([False, False,  True])

In [44]:
s = np.array([12, 3, 4, 3, 1, 2, 2, 4, 6, 7, 2, 4, 8, 5])

In [45]:
np.sort(s)

array([ 1,  2,  2,  2,  3,  3,  4,  4,  4,  5,  6,  7,  8, 12])

In [46]:
sorted(s)

[1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 6, 7, 8, 12]

In [48]:
np.array(sorted(s, reverse=True))

array([12,  8,  7,  6,  5,  4,  4,  4,  3,  3,  2,  2,  2,  1])

In [49]:
np.argsort(s)

array([ 4,  5,  6, 10,  1,  3,  2,  7, 11, 13,  8,  9, 12,  0],
      dtype=int64)

In [50]:
s[13]

5

In [51]:
s.argmax()

0

In [52]:
s

array([12,  3,  4,  3,  1,  2,  2,  4,  6,  7,  2,  4,  8,  5])

In [53]:
s.argmax()

0

In [54]:
s.argmin()

4

In [55]:
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  9],
       [ 1, -3,  4]])

In [56]:
arr1.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [57]:
np.where(1,2,3) # 第一个为true，则输出第二位，否则输出第三位

array(2)

In [58]:
arr2 = np.arange(12).reshape(4,3)

In [59]:
np.where(arr2 > 3, '1', '0')

array([['0', '0', '0'],
       ['0', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [60]:
np.where(arr2>arr1, arr1,arr2)

array([[ 0,  1,  2],
       [ 3,  2,  5],
       [ 4,  5,  8],
       [ 1, -3,  4]])

In [62]:
np.extract(arr1>arr2, arr1)

array([3, 4, 9, 9])