In [1]:
import numpy as np

In [2]:
str_list = ['hello','world']

In [4]:
[i.upper() for i in str_list]

['HELLO', 'WORLD']

In [6]:
np.char.upper(str_list)

array(['HELLO', 'WORLD'], dtype='<U5')

In [7]:
str_list

['hello', 'world']

In [9]:
np.char.add(['中国','国企'],['海军','大阅兵'])

array(['中国海军', '国企大阅兵'], dtype='<U5')

In [10]:
np.char.multiply(['中国','万岁'],3)

array(['中国中国中国', '万岁万岁万岁'], dtype='<U6')

In [11]:
np.char.join([':','-'],['hello','world'])

array(['h:e:l:l:o', 'w-o-r-l-d'], dtype='<U9')

In [15]:
a = ['我想学习一下Python','好好学习一下java']

In [16]:
np.char.replace(a,'学习一下','深入学习')

array(['我想深入学习Python', '好好深入学习java'], dtype='<U12')

In [17]:
np.char.strip(['-电动汽车','海洋科技-','-学习Python'],'-')

array(['电动汽车', '海洋科技', '学习Python'], dtype='<U9')

In [24]:
f = open('D:\desktop\短信.txt',encoding='utf-8').readlines()

In [25]:
f

['截至当前，\n',
 '您的套餐使用情况如下：\n',
 '-流量2017沃派2.0主套餐(首月按天)\n',
 '国内流量\n',
 '已用0.00MB校园沃派专属校区流量放心用-50个月\n',
 '省内基站流量\n',
 '已用0.00MB校园沃派专属4GB全国流量国内流量\n',
 '已用4096.00MB校园沃派专属寒暑假漫游升级送-50个月\n',
 '国内流量\n',
 '已用300.00MB校园沃派专属9G全国流量-50个月\n',
 '国内流量\n',
 '已用0.00MB0元65G全国流量国内流量已用56050.94MB\n',
 '本数据仅供参考。\n',
 '回复“5083”，查看流量半年包余量。\n',
 '回复“1071”，查看手机上网流量。\n',
 '抗击疫情，服务不停！使用手机营业厅，足不出户交话费、查余额、办业务，免流量看电影、玩游戏，点击http://u.10010.cn/khddx，马上拥有】']

In [26]:
f[1]

'您的套餐使用情况如下：\n'

In [29]:
S = f[-1]

In [30]:
S

'抗击疫情，服务不停！使用手机营业厅，足不出户交话费、查余额、办业务，免流量看电影、玩游戏，点击http://u.10010.cn/khddx，马上拥有】'

In [33]:
arr = S.split('，')

In [34]:
arr

['抗击疫情',
 '服务不停！使用手机营业厅',
 '足不出户交话费、查余额、办业务',
 '免流量看电影、玩游戏',
 '点击http://u.10010.cn/khddx',
 '马上拥有】']

In [35]:
arr = np.char.rstrip(arr,'】')

In [36]:
arr

array(['抗击疫情', '服务不停！使用手机营业厅', '足不出户交话费、查余额、办业务', '免流量看电影、玩游戏',
       '点击http://u.10010.cn/khddx', '马上拥有'], dtype='<U25')

In [37]:
arr = np.char.replace(arr,'、',',')

In [38]:
arr

array(['抗击疫情', '服务不停！使用手机营业厅', '足不出户交话费,查余额,办业务', '免流量看电影,玩游戏',
       '点击http://u.10010.cn/khddx', '马上拥有'], dtype='<U25')

In [39]:
np.char.find(arr,'玩游戏')

array([-1, -1, -1,  7, -1, -1])

In [40]:
arr[3][7]

'玩'

In [41]:
np.char.islower(arr,)

array([False, False, False, False,  True, False])

In [42]:
arr

array(['抗击疫情', '服务不停！使用手机营业厅', '足不出户交话费,查余额,办业务', '免流量看电影,玩游戏',
       '点击http://u.10010.cn/khddx', '马上拥有'], dtype='<U25')

In [43]:
np.char.isdigit(arr)

array([False, False, False, False, False, False])

In [45]:
np.char.isalpha(arr)

array([ True, False, False, False, False,  True])

In [46]:
arr

array(['抗击疫情', '服务不停！使用手机营业厅', '足不出户交话费,查余额,办业务', '免流量看电影,玩游戏',
       '点击http://u.10010.cn/khddx', '马上拥有'], dtype='<U25')

In [49]:
np.char.count(arr,'服务')

array([0, 1, 0, 0, 0, 0])